controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_linear_velocity: 0.1
    max_linear_velocity: 1.0
    min_angular_velocity: 0.1
    max_angular_velocity: 1.0

    # List of controller plugins to use
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      vx_samples: 20
      vtheta_samples: 40
      model_predictive_control_rate: 0.05
      path_length_tolerance: 0.5
      lookahead_dist: 0.6
      control_lookahead: 10
      # costmap inflation and sampling parameters
      costmap:
        inflation_radius: 0.1
        resolution: 0.05
