# Exclude map_server and map-related parameters

amcl:
  ros__parameters:
    use_sim_time: true

planner_server:
  ros__parameters:
    use_sim_time: true

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    min_linear_velocity: 0.1
    max_linear_velocity: 1.0
    min_angular_velocity: 0.1
    max_angular_velocity: 1.0
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      vx_samples: 20
      vtheta_samples: 40
      model_predictive_control_rate: 0.05
      path_length_tolerance: 0.5
      lookahead_dist: 0.6

bt_navigator:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.1

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom  # Use 'odom' instead of 'map' to avoid map dependency
      robot_base_frame: base_link
      width: 10.0
      height: 10.0
      resolution: 0.05
      robot_radius: 0.1
